services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: endiaz
      POSTGRES_PASSWORD: Deadlock123
      POSTGRES_DB: db_task_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "7432:5432"

volumes:
  postgres_data:
    driver: local